FROM stockdb_new:latest

ENV DEBIAN_FRONTEND noninteractive
USER root
#RUN pip3 install Dash dash_marvinjs numba xlrd
#RUN LANG=en_US.UTF-8
# setup Stock_db
COPY Stock_DB Stock_DB
COPY TimeStamp TimeStamp
#RUN pip3 install Stock_DB/.
#RUN cd Stock_DB
EXPOSE 8008 5432 8000
USER postgres
CMD ["bash","boot.sh"]
